export const links = [
  {
    id: 1,
    text: "home",
    url: "/",
  },
  {
    id: 2,
    text: "about",
    url: "/about",
  },
  {
    id: 3,
    text: "Jobs",
    url: "/products",
  },
];

export const data = [
  {
    id: 1,
    title: "job 1",
    category: "abc",
    description: "abc def ghi jkl mno",
    salary: 15000,
    location: "colombo",
    hours: 6,
    closeDate: "2023-05-15",
    company: "company 1",
    reviews: 25,
    stars: 4.2,
    featured: true,
  },
  {
    id: 2,
    title: "job 2",
    category: "abc",
    description: "abc def ghi jkl mno",
    salary: 15000,
    location: "colombo",
    hours: 6,
    closeDate: "2023-05-15",
    company: "company 1",
    reviews: 25,
    stars: 4.2,
    featured: true,
  },
  {
    id: 3,
    title: "job 3",
    category: "abc",
    description:
      "abc def ghi jkl mno abc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mnoabc def ghi jkl mno",
    salary: 15000,
    location: "colombo",
    hours: 6,
    closeDate: "2023-05-15",
    company: "company 1",
    reviews: 25,
    stars: 4.2,
    featured: true,
  },
  {
    id: 4,
    title: "job 4",
    category: "abc",
    description: "abc def ghi jkl mno",
    salary: 15000,
    location: "colombo",
    hours: 6,
    closeDate: "2023-05-15",
    company: "company 1",
    reviews: 25,
    stars: 4.2,
    featured: true,
  },
];
