export const links = [
  {
    id: 1,
    text: "home",
    url: "/",
  },
  {
    id: 2,
    text: "about",
    url: "/about",
  },
  {
    id: 3,
    text: "Jobs",
    url: "/products",
  },
];

export const data = [
  {
    id: 1,
    title: "Waiter",
    description:
      "Seeking a part-time waiter to join our team. As a waiter, you will play a crucial role in providing exceptional customer service during evenings and weekends. Your responsibilities include taking orders, serving food and beverages, and ensuring a pleasant dining experience for our valued guests.",
    salary: 500,
    location: "colombo",
    hours: 6,
    closeDate: "2023-09-30",
    company: "Spice Delight",
    reviews: 35,
    stars: 4.2,
    featured: true,
  },
  {
    id: 2,
    title: "Waiter",
    description:
      "Join as a part-time waiter and become an integral part of creating memorable dining experiences. Your role involves welcoming guests, recommending menu items, taking orders, and ensuring customer satisfaction. Evenings and weekends are when we need your expertise the most.",
    salary: 800,
    location: "galle",
    hours: 5,
    closeDate: "2023-10-31",
    company: "Ocean View Bistro",
    reviews: 45,
    stars: 4.5,
    featured: true,
  },
  {
    id: 3,
    title: "Waiter",
    description:
      "Looking for a part-time waiter to join our cozy cafe in Kandy. As a waiter, you will serve coffee and pastries, provide friendly customer service, and maintain a warm and welcoming atmosphere for our patrons. It's the perfect position for those who enjoy a relaxed cafe environment.",
    salary: 750,
    location: "mathara",
    hours: 6,
    closeDate: "2023-11-30",
    company: "Cafe Latte",
    reviews: 20,
    stars: 4.0,
    featured: true,
  },
  {
    id: 4,
    title: "Waiter",
    description:
      "Seeking a part-time waiter with excellent communication skills. Join our team and be responsible for taking customer orders, serving meals, handling inquiries, and ensuring that every guest has a delightful dining experience.",
    salary: 500,
    location: "kaluthara",
    hours: 5,
    closeDate: "2023-12-31",
    company: "Beachside Bistro",
    reviews: 40,
    stars: 4.3,
    featured: false,
  },
  {
    id: 5,
    title: "Waiter",
    description:
      "Hiring a part-time waiter to work during evenings. In this fast-paced environment, you'll assist in providing top-notch service, teamwork, and ensuring the smooth flow of restaurant operations.",
    salary: 500,
    location: "gampaha",
    hours: 4,
    closeDate: "2024-01-31",
    company: "Central Eats",
    reviews: 55,
    stars: 4.6,
    featured: true,
  },
  {
    id: 6,
    title: "Waiter",
    description:
      "Join as a part-time waiter, focusing on handling lunch shifts during weekdays. Your responsibilities include setting tables, serving lunches, and ensuring a pleasant dining experience for our lunchtime patrons.",
    salary: 800,
    location: "rathnapura",
    hours: 6,
    closeDate: "2023-09-30",
    company: "Lunch Box Cafe",
    reviews: 25,
    stars: 4.1,
    featured: true,
  },
  {
    id: 7,
    title: "Waiter",
    description:
      "Inviting candidates as a part-time waiter in our popular restaurant in Matara. You'll serve a diverse menu, provide menu recommendations, and deliver exceptional table service to our guests.",
    salary: 850,
    location: "kurunagala",
    hours: 4,
    closeDate: "2023-10-31",
    company: "Matara Grill",
    reviews: 60,
    stars: 4.7,
    featured: true,
  },
  {
    id: 8,
    title: "Waiter",
    description:
      "Offering a part-time waiter position with a strong emphasis on teamwork and ensuring customer satisfaction. Collaborate with fellow team members to provide an outstanding dining experience for our guests.",
    salary: 2500,
    location: "colombo",
    hours: 5,
    closeDate: "2023-11-30",
    company: "Hikka Breeze",
    reviews: 30,
    stars: 4.4,
    featured: false,
  },
  {
    id: 9,
    title: "Waiter",
    description:
      "Seeking a part-time waiter who is passionate about food service. Your role will involve providing excellent customer service, sharing your food knowledge, and contributing to the unique dining experience in the historic Galle Fort.",
    salary: 850,
    location: "galle",
    hours: 6,
    closeDate: "2023-12-31",
    company: "Fort Cuisine",
    reviews: 38,
    stars: 4.2,
    featured: true,
  },
  {
    id: 10,
    title: "Waiter",
    description:
      "Looking for a part-time waiter. You'll provide family-friendly service, assist with traditional cuisine, and contribute to a warm and welcoming dining environment, particularly on weekends.",
    salary: 800,
    location: "mathara",
    hours: 5,
    closeDate: "2024-01-31",
    company: "Rice & Spice",
    reviews: 22,
    stars: 4.0,
    featured: true,
  },
  {
    id: 11,
    title: "Tutor",
    description:
      "Seeking a dedicated part-time tutor. You will have the opportunity to help students improve their math and science skills through personalized tutoring sessions. Whether it's algebra, biology, or chemistry, your expertise will play a crucial role in guiding students toward academic success. Salary is given per hour.",
    salary: 3000,
    location: "kaluthara",
    hours: 3,
    closeDate: "2023-09-30",
    company: "TutorMe",
    reviews: 25,
    stars: 4.3,
    featured: true,
  },
  {
    id: 12,
    title: "Tutor",
    description:
      "Join as a part-time English tutor and make a significant impact on students' language development. Your role will involve assisting students in enhancing their language skills, including grammar and language instruction. With flexible evening and weekend hours, you can create a positive learning experience. Salary is given per hour.",
    salary: 2000,
    location: "gampaha",
    hours: 3,
    closeDate: "2023-10-31",
    company: "Language Excellence",
    reviews: 20,
    stars: 4.2,
    featured: true,
  },
  {
    id: 13,
    title: "Tutor",
    description:
      "Looking for a part-time science tutor who is passionate about biology and chemistry. You'll have the opportunity to share your knowledge and inspire students to excel in their science studies. This flexible position allows you to contribute to students' academic growth. Salary is given per hour.",
    salary: 2000,
    location: "rathnapura",
    hours: 2,
    closeDate: "2023-11-30",
    company: "Science Wizards",
    reviews: 18,
    stars: 4.0,
    featured: false,
  },
  {
    id: 14,
    title: "Tutor",
    description:
      "Hiring a part-time math tutor to assist students in mastering mathematical concepts. With flexible evening hours, you will guide students in areas such as mathematics and algebra, helping them build a strong foundation in these subjects.Salary is given per hour.",
    salary: 2500,
    location: "kurunagala",
    hours: 3,
    closeDate: "2023-12-31",
    company: "MathGenius Tutors",
    reviews: 30,
    stars: 4.4,
    featured: true,
  },
  {
    id: 15,
    title: "Tutor",
    description:
      "Join as a part-time tutor and provide support in various subjects, helping students achieve academic success. Your role will include tutoring in multiple subjects and using effective communication to enhance students' learning experiences. Salary is given per hour.",
    salary: 3500,
    location: "colombo",
    hours: 4,
    closeDate: "2024-01-31",
    company: "Smart Prep",
    reviews: 35,
    stars: 4.1,
    featured: true,
  },
  {
    id: 16,
    title: "Tutor",
    description:
      "Offering a part-time tutor position to help students with mathematics and science subjects on weekends. As a mentor, you will guide students toward success in these crucial areas, making a positive impact on their academic journeys. Salary is given per hour.",
    salary: 2500,
    location: "galle",
    hours: 5,
    closeDate: "2023-09-30",
    company: "EduPro",
    reviews: 28,
    stars: 4.3,
    featured: true,
  },
  {
    id: 17,
    title: "Tutor",
    description:
      "Looking for a part-time tutor to assist students with various subjects. This flexible position offers a positive work environment where you can use your subject expertise and positive attitude to support students in their learning. Salary is given per hour.",
    salary: 2000,
    location: "mathara",
    hours: 4,
    closeDate: "2023-10-31",
    company: "LearnWell Institute",
    reviews: 22,
    stars: 4.0,
    featured: false,
  },
  {
    id: 18,
    title: "Tutor",
    description:
      "Seeking a part-time English tutor to improve students' language skills. Your role will include language instruction, helping students become more proficient in English. Patience and effective teaching techniques are key in this position. Salary is given per hour.",
    salary: 1500,
    location: "kaluthara",
    hours: 3,
    closeDate: "2023-11-30",
    company: "LanguageMasters",
    reviews: 26,
    stars: 4.2,
    featured: true,
  },
  {
    id: 19,
    title: "Tutor",
    description:
      "Hiring a part-time tutor to provide support in mathematics and physics subjects. Your flexibility in working hours will accommodate students' needs, and your expertise will help them excel in these subjects. Salary is given per hour.",
    salary: 3000,
    location: "gampaha",
    hours: 4,
    closeDate: "2023-12-31",
    company: "Academic Aces",
    reviews: 32,
    stars: 4.4,
    featured: true,
  },
  {
    id: 20,
    title: "Tutor",
    description:
      "In need of a part-time tutor to assist students in various subjects on weekends. Your role will involve supportive teaching to help students reach their full potential academically. Salary is given per hour.",
    salary: 2500,
    location: "rathnapura",
    hours: 4,
    closeDate: "2024-01-31",
    company: "Student Success Academy",
    reviews: 27,
    stars: 4.1,
    featured: true,
  },
  {
    id: 21,
    title: "Data Entry Clerk",
    description:
      "Join our team as a Data Entry Clerk and utilize your strong attention to detail and data entry skills. Salary is given per hour.",
    salary: 5000,
    location: "kurunagala",
    hours: 6,
    closeDate: "2023-09-30",
    company: "DataTech Solutions",
    review: 24,
    stars: 4.5,
    featured: true,
  },
  {
    id: 22,
    title: "Data Entry Clerk",
    description:
      "We are hiring a Data Entry Clerk to work flexible hours.Attention to detail is a must.Salary is given per hour.",
    salary: 3000,
    location: "colombo",
    hours: 4,
    closeDate: "2023-10-31",
    company: "DataPro Services",
    review: 45,
    stars: 4.0,
    featured: false,
  },
  {
    id: 23,
    title: "Data Entry Clerk",
    description:
      "Looking for a Data Entry Clerk with attention to detail.Salary is given per hour",
    salary: 4500,
    location: "galle",
    hours: 6,
    closeDate: "2023-11-30",
    company: "InfoTech Solutions",
    review: 30,
    stars: 4.2,
    featured: true,
  },
  {
    id: 24,
    title: "Data Entry Clerk",
    description:
      "Join our team as a Data Entry Clerk. Full-time, rotating shifts.Salary is given per hour.",
    salary: 5000,
    location: "mathara",
    hours: 6,
    closeDate: "2023-12-31",
    company: "DataWorks Innovations",
    review: 55,
    stars: 4.0,
    featured: true,
  },
  {
    id: 25,
    title: "Data Entry Clerk",
    description:
      "Immediate opening for a Data Entry Clerk with strong attention to detail.Salary is given per hour. ",
    salary: 6000,
    location: "kaluthara",
    hours: 5,
    closeDate: "2024-01-31",
    company: "DataTech Pro",
    review: 41,
    stars: 4.7,
    featured: true,
  },
  {
    id: 26,
    title: "Data Entry Clerk",
    description:
      "Seeking a Data Entry Clerk with excellent data entry skills.Salary is given per hour .",
    salary: 3500,
    location: "gampaha",
    hours: 6,
    closeDate: "2023-09-30",
    company: "DataMasters Inc.",
    review: 32,
    stars: 3.4,
    featured: false,
  },
  {
    id: 27,
    title: "Data Entry Clerk",
    description:
      "Data Entry Clerk position available with a focus on accuracy.Salary is given per hour.",
    salary: 6500,
    location: "rathnapura",
    hours: 7,
    closeDate: "2023-10-31",
    company: "DataWave Solutions",
    review: 55,
    stars: 4.8,
    featured: true,
  },
  {
    id: 28,
    title: "Data Entry Clerk",
    description:
      "Immediate opening for a Data Entry Clerk.Salary is given per hour.",
    salary: 3200,
    location: "kurunagala",
    hours: 5,
    closeDate: "2023-11-30",
    company: "DataFlow Inc.",
    review: 28,
    stars: 3.2,
    featured: false,
  },
  {
    id: 29,
    title: "Data Entry Clerk",
    description:
      "Seeking a Data Entry Clerk with strong data input skills.Salary is given per hour.",
    salary: 5000,
    location: "colombo",
    hours: 5,
    closeDate: "2023-12-31",
    company: "DataMagic Services",
    review: "Good pay, challenging work",
    stars: 4.6,
    featured: true,
  },
  {
    id: 30,
    title: "Data Entry Clerk",
    description:
      "Data Entry Clerk position available with a focus on accuracy.Salary is given per hour.",
    salary: 3000,
    location: "galle",
    hours: 4,
    closeDate: "2024-01-31",
    company: "DataWorld Solutions",
    review: 34,
    stars: 3.3,
    featured: false,
  },
  {
    id: 31,
    title: "Security Officer",
    description:
      "Security Officer position available. Must have strong communication skills and salary is given per hour.",
    salary: 2000,
    location: "mathara",
    hours: 8,
    closeDate: "2023-09-30",
    company: "SecureGuard Solutions",
    review: 61,
    stars: 4.5,
    featured: true,
  },
  {
    id: 32,
    title: "Security Officer",
    description:
      "Hiring a Security Officer with experience in access control.Salary is given per hour. ",
    salary: 1000,
    location: "kaluthara",
    hours: 8,
    closeDate: "2023-10-31",
    company: "Guardian Security Services",
    review: 35,
    stars: 4.2,
    featured: false,
  },
  {
    id: 33,
    title: "Security Officer",
    description:
      "Immediate opening for a Security Officer.Salary is given per hour.",
    salary: 1800,
    location: "gampaha",
    hours: 9,
    closeDate: "2023-11-30",
    company: "SafeZone Security Services",
    review: 41,
    stars: 3.9,
    featured: true,
  },
  {
    id: 34,
    title: "Security Officer",
    description:
      "Join our team as a Security Officer.Full-time, night shifts.Salary is given per hour. ",
    salary: 2000,
    location: "rathnapura",
    hours: 8,
    closeDate: "2023-12-31",
    company: "SafetyFirst Security",
    review: 54,
    stars: 4.8,
    featured: true,
  },
  {
    id: 35,
    title: "Security Officer",
    description:
      "Security Officer needed for a full-time position. Salary is given per hour. Knowledge of security systems required.",
    salary: 1200,
    location: "kurunagala",
    hours: 7,
    closeDate: "2024-01-31",
    company: "SecureNet Solutions",
    review: 38,
    stars: 3.6,
    featured: false,
  },
  {
    id: 36,
    title: "Security Officer",
    description:
      "We are hiring a Security Officer with strong problem-solving skills.Salary is given per hour.",
    salary: 1800,
    location: "colombo",
    hours: 7,
    closeDate: "2023-09-30",
    company: "SecurityPro Inc.",
    review: 58,
    stars: 4.2,
    featured: true,
  },
  {
    id: 37,
    title: "Security Officer",
    description:
      "Security Officer position available.Salary is given per hour.",
    salary: 1200,
    location: "galle",
    hours: 8,
    closeDate: "2023-10-31",
    company: "SecureGuard Solutions",
    review: 29,
    stars: 4.4,
    featured: false,
  },
  {
    id: 38,
    title: "Security Officer",
    description:
      "Join our team as a Security Officer and salary is given per hour., flexible shifts available.",
    salary: 2000,
    location: "mathara",
    hours: 8,
    closeDate: "2023-11-30",
    company: "Guardian Security Services",
    review: "Good entry-level job",
    stars: 4.0,
    featured: true,
  },
  {
    id: 39,
    title: "Security Officer",
    description:
      "Seeking a Security Officer with experience in surveillance.Salary is given per hour. Full-time, rotating shifts.",
    salary: 1100,
    location: "kaluthara",
    hours: 8,
    closeDate: "2023-12-31",
    company: "SecureNet Solutions",
    review: 31,
    stars: 3.3,
    featured: false,
  },
  {
    id: 40,
    title: "Security Officer",
    description:
      "Security Officer position available.Salary is given per hour. Full-time, Monday to Friday.",
    salary: 1000,
    location: "gampaha",
    hours: 8,
    closeDate: "2024-01-31",
    company: "SecurityExperts Inc.",
    review: 35,
    stars: 3.2,
    featured: false,
  },
  {
    id: 41,
    title: "Web Developer",
    description:
      "Front-end Web Developer with experience in HTML, CSS, and JavaScript.Salary is given per hour",
    salary: 2000,
    location: "rathnapura",
    hours: 3,
    closeDate: "2023-09-30",
    company: "Tech Solutions Inc.",
    reviews: 45,
    stars: 4.5,
    featured: true,
  },
  {
    id: 42,
    title: "Web Developer",
    description:
      "Back-end Web Developer with expertise in Node.js and databases.Salary is given per hour",
    salary: 3000,
    location: "kurunagala",
    hours: 4,
    closeDate: "2023-10-31",
    company: "WebTech Innovations",
    reviews: 30,
    stars: 4.2,
    featured: false,
  },
  {
    id: 43,
    title: "Web Developer",
    description:
      "Full-stack Web Developer with skills in React and Express.Salary is given per hour",
    salary: 2500,
    location: "colombo",
    hours: 3,
    closeDate: "2023-11-30",
    company: "Digital Solutions Co.",
    reviews: 20,
    stars: 4.0,
    featured: true,
  },
  {
    id: 44,
    title: "Web Developer",
    description:
      "Junior Web Developer position for recent graduates.Salary is given per hour",
    salary: 2000,
    location: "galle",
    hours: 4,
    closeDate: "2023-12-31",
    company: "Innovative Web Services",
    reviews: 15,
    stars: 3.8,
    featured: false,
  },
  {
    id: 45,
    title: "Web Developer",
    description:
      "Senior Web Developer with over 5 years of experience.Salary is given per hour",
    salary: 3000,
    location: "mathara",
    hours: 3,
    closeDate: "2024-01-31",
    company: "TechMasters Inc.",
    reviews: 60,
    stars: 4.8,
    featured: true,
  },
  {
    id: 46,
    title: "Web Developer",
    description:
      "Front-end Developer with expertise in responsive web design.Salary is given per hour",
    salary: 4000,
    location: "kaluthara",
    hours: 2,
    closeDate: "2023-09-30",
    company: "WebCrafters Ltd.",
    reviews: 25,
    stars: 4.3,
    featured: true,
  },
  {
    id: 47,
    title: "Web Developer",
    description:
      "UI/UX Designer and Developer for mobile and web applications.Salary is given per hour",
    salary: 3500,
    location: "gampaha",
    hours: 3,
    closeDate: "2023-10-31",
    company: "Creative Designs Inc.",
    reviews: 35,
    stars: 4.4,
    featured: false,
  },
  {
    id: 48,
    title: "Web Developer",
    description:
      "E-commerce Web Developer specializing in online retail platforms.Salary is given per hour",
    salary: 2000,
    location: "rathnapura",
    hours: 4,
    closeDate: "2023-11-30",
    company: "E-commerce Innovations",
    reviews: 18,
    stars: 4.1,
    featured: true,
  },
  {
    id: 49,
    title: "Web Developer",
    description:
      "WordPress Developer for custom website development projects.Salary is given per hour",
    salary: 2500,
    location: "kurunagala",
    hours: 3,
    closeDate: "2023-12-31",
    company: "WP Wizards LLC",
    reviews: 22,
    stars: 4.0,
    featured: false,
  },
  {
    id: 50,
    title: "Web Developer",
    description:
      "Remote Web Developer position for a distributed software team.Salary is given per hour",
    salary: 3000,
    location: "colombo",
    hours: 2,
    closeDate: "2024-01-31",
    company: "Digital Nomad Solutions",
    reviews: 28,
    stars: 4.6,
    featured: true,
  },
  {
    id: 51,
    title: "Delivery Driver",
    description:
      "Delivery driver needed for local food delivery service.Salary is given per hour",
    salary: 1000,
    location: "galle",
    hours: 2,
    closeDate: "2023-09-30",
    company: "Quick Bites Delivery",
    reviews: 25,
    stars: 4.2,
    featured: true,
  },
  {
    id: 52,
    title: "Delivery Driver",
    description:
      "Package delivery driver for a courier company.Salary is given per hour",
    salary: 1500,
    location: "mathara",
    hours: 4,
    closeDate: "2023-10-31",
    company: "Swift Couriers Inc.",
    reviews: 30,
    stars: 4.0,
    featured: false,
  },
  {
    id: 53,
    title: "Delivery Driver",
    description:
      "Medical supply delivery driver for healthcare facilities.Salary is given per hour",
    salary: 2000,
    location: "kaluthara",
    hours: 4,
    closeDate: "2023-11-30",
    company: "Health Express Logistics",
    reviews: 15,
    stars: 3.8,
    featured: true,
  },
  {
    id: 54,
    title: "Delivery Driver",
    description:
      "Pizza delivery driver for a local pizzeria.Salary is given per hour",
    salary: 2000,
    location: "gampaha",
    hours: 4,
    closeDate: "2023-12-31",
    company: "Pizza Haven",
    reviews: 20,
    stars: 4.5,
    featured: false,
  },
  {
    id: 55,
    title: "Delivery Driver",
    description:
      "Amazon delivery driver for package distribution.Salary is given per hour",
    salary: 1800,
    location: "rathnapura",
    hours: 3,
    closeDate: "2024-01-31",
    company: "Amazon Logistics",
    reviews: 40,
    stars: 4.4,
    featured: true,
  },
  {
    id: 56,
    title: "Delivery Driver",
    description:
      "Local pharmacy delivery driver for prescription medications.Salary is given per hour",
    salary: 1000,
    location: "kurunagala",
    hours: 2,
    closeDate: "2023-09-30",
    company: "MediCare Delivery Services",
    reviews: 12,
    stars: 3.7,
    featured: true,
  },
  {
    id: 57,
    title: "Delivery Driver",
    description:
      "Grocery delivery driver for a grocery delivery startup.Salary is given per hour",
    salary: 800,
    location: "colombo",
    hours: 2,
    closeDate: "2023-10-31",
    company: "FreshCart Delivery",
    reviews: 10,
    stars: 4.1,
    featured: false,
  },
  {
    id: 58,
    title: "Delivery Driver",
    description:
      "Courier driver for same-day document and package deliveries.Salary is given per hour",
    salary: 1000,
    location: "galle",
    hours: 2,
    closeDate: "2023-11-30",
    company: "ExpressDocs Couriers",
    reviews: 18,
    stars: 4.3,
    featured: true,
  },
  {
    id: 59,
    title: "Delivery Driver",
    description:
      "Food delivery driver for a popular restaurant chain.Salary is given per hour",
    salary: 1500,
    location: "mathara",
    hours: 2,
    closeDate: "2023-12-31",
    company: "Gourmet Delights",
    reviews: 22,
    stars: 4.2,
    featured: false,
  },
  {
    id: 60,
    title: "Delivery Driver",
    description:
      "Specialized delivery driver for fragile and high-value items.Salary is given per hour",
    salary: 1200,
    location: "kaluthara",
    hours: 2,
    closeDate: "2024-01-31",
    company: "SecureShip Logistics",
    reviews: 8,
    stars: 4.6,
    featured: true,
  },
  {
    id: 61,
    title: "typesetter",
    description:
      "We are seeking a skilled typesetter with expertise in Adobe InDesign, typography, and layout design to join our team at PrintPro Solutions in Colombo. You will be responsible for formatting and designing printed materials. This part-time position.",
    salary: 800,
    location: "gampaha",
    hours: 4,
    closeDate: "2023-09-30",
    company: "PrintPro Solutions",
    reviews: 38,
    stars: 4,
    featured: true,
  },
  {
    id: 62,
    title: "typesetter",
    description:
      "Join PageTurner Publishing in Kandy, Sri Lanka, as a typesetter proficient in QuarkXPress for book formatting. This part-time position.",
    salary: 600,
    location: "rathnapura",
    hours: 3,
    closeDate: "2023-10-31",
    company: "PageTurner Publishing",
    reviews: 40,
    stars: 3.8,
    featured: false,
  },
  {
    id: 63,
    title: "typesetter",
    description:
      "MathTech Publications is looking for a typesetter with LaTeX expertise for mathematical content.Proficiency in Adobe FrameMaker is required. ",
    salary: 900,
    location: "kurunagala",
    hours: 5,
    closeDate: "2023-11-30",
    company: "MathTech Publications",
    reviews: 25,
    stars: 4.5,
    featured: false,
  },
  {
    id: 64,
    title: "typesetter",
    description:
      "AdMasters is seeking an experienced part-time typesetter with Adobe Creative Suite skills for advertising materials in Galle.",
    salary: 650,
    location: "colombo",
    hours: 4,
    closeDate: "2023-12-31",
    company: "AdMasters",
    reviews: 35,
    stars: 4.1,
    featured: true,
  },
  {
    id: 65,
    title: "typesetter",
    description:
      "PrintCrafters Ltd. is hiring a part-time typesetter with strong graphic design skills, including Photoshop and Illustrator, in Negombo.",
    salary: 750,
    location: "galle",
    hours: 5,
    closeDate: "2024-01-31",
    company: "PrintCrafters Ltd.",
    reviews: 20,
    stars: 4.2,
    featured: false,
  },
  {
    id: 66,
    title: "typesetter",
    description:
      "EduTech Solutions is hiring a part-time typesetter with Adobe InDesign skills for e-learning materials in Jaffna. Proficiency in Adobe FrameMaker is required.",
    salary: 850,
    location: "mathara",
    hours: 5,
    closeDate: "2023-09-30",
    company: "EduTech Solutions",
    reviews: 40,
    stars: 4.0,
    featured: false,
  },
  {
    id: 67,
    title: "typesetter",
    description:
      "WordSmith Publishers is seeking a part-time typesetter with expertise in Microsoft Word for manuscript formatting in Matara. You'll help format advertising materials for clients.",
    salary: 900,
    location: "kaluthara",
    hours: 6,
    closeDate: "2023-10-31",
    company: "WordSmith Publishers",
    reviews: 28,
    stars: 3.7,
    featured: false,
  },
  {
    id: 68,
    title: "typesetter",
    description:
      "TechDocs International is seeking a part-time typesetter with Adobe FrameMaker skills for technical documents.",
    salary: 550,
    location: "gampaha",
    hours: 8,
    closeDate: "2023-11-30",
    company: "TechDocs International",
    reviews: 47,
    stars: 4.3,
    featured: true,
  },
  {
    id: 69,
    title: "typesetter",
    description:
      "MagazineMakers is hiring a part-time typesetter proficient in Scribus for magazine layout in Batticaloa. This position requires expertise in Photoshop and Illustrator for graphic design and layout.",
    salary: 800,
    location: "rathnapura",
    hours: 7,
    closeDate: "2023-12-31",
    company: "MagazineMakers",
    reviews: 33,
    stars: 3.9,
    featured: false,
  },
  {
    id: 70,
    title: "typesetter",
    description:
      "BookCrafters is offering a part-time typesetter position for someone passionate about designing beautiful books in Trincomalee, Sri Lanka. Proficiency in Adobe PageMaker is a plus.",
    salary: 750,
    location: "kurunagala",
    closeDate: "2024-01-31",
    hours: 5,
    company: "BookCrafters",
    reviews: 20,
    stars: 4.0,
    featured: true,
  },
  {
    id: 71,
    title: "fitness instructor",
    description:
      "Join FitLife Gym in Colombo, Sri Lanka, as a part-time fitness instructor. Your role will involve leading fitness classes, guiding participants, and providing expert instruction in cardio, strength training, and yoga. Strong communication and motivation skills are essential for this role. Experience in personal training is a plus.",
    salary: 4000,
    location: "colombo",
    hours: 4,
    closeDate: "2023-09-30",
    company: "FitLife Gym",
    reviews: 45,
    stars: 4.0,
    featured: true,
  },
  {
    id: 72,
    title: "fitness instructor",
    description:
      "Be a part-time fitness instructor at WellnessHub in Kandy, Sri Lanka. You'll lead group fitness sessions and provide personalized fitness guidance to clients. A background in nutrition and dietary advice is highly valued.",
    salary: 3600,
    location: "galle",
    hours: 3,
    closeDate: "2023-10-31",
    company: "WellnessHub",
    reviews: 40,
    stars: 3.9,
    featured: false,
  },
  {
    id: 73,
    title: "fitness instructor",
    description:
      "FitnessFusion Studios is hiring a part-time fitness instructor in Sri Lanka. Your responsibilities include conducting high-intensity interval training (HIIT) classes, circuit training, and ensuring a safe workout environment.",
    salary: 5500,
    location: "mathara",
    hours: 5,
    closeDate: "2023-11-30",
    company: "FitnessFusion Studios",
    reviews: 30,
    stars: 4.6,
    featured: false,
  },
  {
    id: 74,
    title: "fitness instructor",
    description:
      "Become a part-time fitness instructor at FlexFit Gym in Galle, Sri Lanka. Lead fitness classes such as Zumba, Pilates, and strength training. Knowledge of injury prevention and first aid is a plus.",
    salary: 4800,
    location: "kaluthara",
    hours: 6,
    closeDate: "2023-12-31",
    company: "FlexFit Gym",
    reviews: 25,
    stars: 3.1,
    featured: true,
  },
  {
    id: 75,
    title: "fitness instructor",
    description:
      "FitZone Fitness Center is seeking a part-time fitness instructor with expertise in spinning and indoor cycling classes. Instruct and motivate participants to achieve their fitness goals.",
    salary: 2500,
    location: "gampaha",
    hours: 3,
    closeDate: "2024-01-31",
    company: "FitZone Fitness Center",
    reviews: 35,
    stars: 4.2,
    featured: false,
  },
  {
    id: 76,
    title: "fitness instructor",
    description:
      "Join HealthFirst Wellness Center in Jaffna, Sri Lanka, as a part-time fitness instructor. Conduct group fitness classes and provide individualized fitness assessments. Certification in CPR and AED is a plus.",
    salary: 6000,
    location: "rathnapura",
    hours: 7,
    closeDate: "2023-09-30",
    company: "HealthFirst Wellness Center",
    reviews: 38,
    stars: 4.0,
    featured: false,
  },
  {
    id: 77,
    title: "fitness instructor",
    description:
      "BodyBoost Fitness is looking for a part-time fitness instructor in Matara, Sri Lanka. Lead boot camp-style classes and promote a healthy lifestyle. Knowledge of sports nutrition is an advantage.",
    salary: 3500,
    location: "kurunagala",
    hours: 2,
    closeDate: "2023-10-31",
    company: "BodyBoost Fitness",
    reviews: 40,
    stars: 3.7,
    featured: false,
  },
  {
    id: 78,
    title: "fitness instructor",
    description:
      "TrainXperience Fitness Studio is seeking a part-time fitness instructor with experience in TRX suspension training and bodyweight exercises. Conduct group sessions and assist clients in achieving their fitness goals.",
    salary: 4000,
    location: "colombo",
    hours: 3,
    closeDate: "2023-11-30",
    company: "TrainXperience Fitness Studio",
    reviews: 37,
    stars: 4.3,
    featured: true,
  },
  {
    id: 79,
    title: "fitness instructor",
    description:
      "Yoga in Batticaloa, Sri Lanka, is hiring a part-time fitness instructor specializing in yoga and meditation. Lead classes that focus on mindfulness, flexibility, and relaxation techniques.",
    salary: 4200,
    location: "galle",
    hours: 4,
    closeDate: "2023-12-31",
    company: "Yoga",
    reviews: 41,
    stars: 3.9,
    featured: false,
  },
  {
    id: 80,
    title: "fitness instructor",
    description:
      "TrainSmart Fitness Club is offering a part-time fitness instructor position in Trincomalee, Sri Lanka. Lead various fitness classes and assist clients in creating personalized workout plans.",
    salary: 3000,
    location: "mathara",
    hours: 3,
    closeDate: "2024-01-31",
    company: "TrainSmart Fitness Club",
    reviews: 42,
    stars: 4.0,
    featured: true,
  },
  {
    id: 81,
    title: "Bartender",
    description:
      "Join our cozy neighborhood bar as a part-time bartender. We're looking for someone with excellent cocktail-making skills and a friendly personality.salary will be paid per hour.",
    salary: 500,
    location: "kaluthara",
    hours: 6,
    closeDate: "2023-09-30",
    company: "Harbor Haven Pub",
    reviews: 15,
    stars: 4.2,
    featured: true,
  },
  {
    id: 82,
    title: "Bartender",
    description:
      "Work as a part-time bartender at our beachside resort. Create tropical drinks and provide exceptional service to our guests.Salary will be paid per hour.",
    salary: 450,
    location: "gampaha",
    hours: 5,
    closeDate: "2023-10-31",
    company: "Sunset Beach Resort Bar",
    reviews: 12,
    stars: 4.0,
    featured: false,
  },
  {
    id: 83,
    title: "Bartender",
    description:
      "Join our team as a part-time bartender in the heart of Kandy. Must be skilled in mixology and available for weekend shifts.Salary will be paid per hour.",
    salary: 500,
    location: "rathnapura",
    hours: 5,
    closeDate: "2023-11-30",
    company: "Hillside Spirits Lounge",
    reviews: 9,
    stars: 4.1,
    featured: false,
  },
  {
    id: 84,
    title: "Bartender",
    description:
      "Looking for a part-time bartender to join our vibrant nightclub in Colombo. Create exciting cocktails and provide high-energy entertainment.Salary will be paid per hour.",
    salary: 550,
    location: "kurunagala",
    hours: 7,
    closeDate: "2023-12-31",
    company: "Electric Groove Nightclub",
    reviews: 20,
    stars: 4.3,
    featured: true,
  },
  {
    id: 85,
    title: "Bartender",
    description:
      "Join our part-time bartender team at a trendy lounge in Galle. Create signature cocktails and be part of a vibrant nightlife scene.Salary will be paid per hour.",
    salary: 400,
    location: "colombo",
    hours: 5,
    closeDate: "2024-01-31",
    company: "Luxe Lounge Galle",
    reviews: 14,
    stars: 4.4,
    featured: false,
  },
  {
    id: 86,
    title: "Bartender",
    description:
      "Work as a part-time bartender in a boutique hotel in Ella. Create memorable cocktails and provide personalized service to guests.Salary will be paid per hour.",
    salary: 550,
    location: "galle",
    hours: 6,
    closeDate: "2023-09-30",
    company: "galle Heights Boutique Hotel",
    reviews: 8,
    stars: 4.5,
    featured: true,
  },
  {
    id: 87,
    title: "Bartender",
    description:
      "Join our part-time bartender team at a lively bar in Hikkaduwa. Mix cocktails and be part of the beach nightlife.Salary will be paid per hour.",
    salary: 400,
    location: "mathara",
    hours: 5,
    closeDate: "2023-10-31",
    company: "Beach Vibes Bar",
    reviews: 11,
    stars: 4.0,
    featured: false,
  },
  {
    id: 88,
    title: "Bartender",
    description:
      "Work as a part-time bartender at a lakeside restaurant in Nuwara Eliya. Create cocktails with a view and enhance our guests' dining experience.Salary will be paid per hour.",
    salary: 550,
    location: "kaluthara",
    hours: 4,
    closeDate: "2023-11-30",
    company: "Lakeside Breeze Restaurant",
    reviews: 10,
    stars: 4.2,
    featured: true,
  },
  {
    id: 89,
    title: "Bartender",
    description:
      "Join our part-time bartender team at a beachfront bar in Mirissa. Craft tropical cocktails and be part of the laid-back beach atmosphere.Salary will be paid per hour.",
    salary: 800,
    location: "gampaha",
    hours: 6,
    closeDate: "2023-12-31",
    company: "Mirissa Waves Beach Bar",
    reviews: 13,
    stars: 4.3,
    featured: false,
  },
  {
    id: 90,
    title: "Bartender",
    description:
      "Looking for a part-time bartender to join our historic colonial-era bar in Galle Fort. Serve classic cocktails in a unique setting.Salary will be paid per hour.",
    salary: 450,
    location: "rathnapura",
    hours: 6,
    closeDate: "2024-01-31",
    company: "Colonial Heritage Bar",
    reviews: 7,
    stars: 4.1,
    featured: false,
  },

  {
    id: 91,
    title: "Assistant Photographer",
    description:
      "Be part of our photography team as a part-time assistant. Help in preparing for photoshoots and post-processing.Salary will be paid per hour.",
    salary: 350,
    location: "kurunagala",
    hours: 6,
    closeDate: "2023-09-30",
    company: "Focus Lens Photography",
    reviews: 6,
    stars: 4.0,
    featured: false,
  },
  {
    id: 92,
    title: "Assistant Photographer",
    description:
      "Join our creative team as a part-time assistant photographer. Assist in capturing weddings and events.Salary will be paid per hour.",
    salary: 300,
    location: "colombo",
    hours: 7,
    closeDate: "2023-10-31",
    company: "Eternal  Photography",
    reviews: 5,
    stars: 4.1,
    featured: false,
  },
  {
    id: 93,
    title: "Assistant Photographer",
    description:
      "Work as a part-time assistant photographer and assist in capturing special moments. Perfect for photography enthusiasts.Salary will be paid per hour.",
    salary: 450,
    location: "galle",
    hours: 8,
    closeDate: "2023-11-30",
    company: "Shutter Speed Creations",
    reviews: 9,
    stars: 4.3,
    featured: true,
  },
  {
    id: 94,
    title: "Assistant Photographer",
    description:
      "Join our photography team as a part-time assistant. Help capture stunning landscapes and portraits.Salary will be paid per hour.",
    salary: 300,
    location: "mathara",
    hours: 5,
    closeDate: "2023-12-31",
    company: "Nature's Frame Photography",
    reviews: 7,
    stars: 4.4,
    featured: false,
  },
  {
    id: 95,
    title: "Assistant Photographer",
    description:
      "Be part of our photography team as a part-time assistant. Assist in product photography and editing.Salary will be paid per hour.",
    salary: 450,
    location: "kaluthara",
    hours: 6,
    closeDate: "2024-01-31",
    company: "Ella Clicks Photography",
    reviews: 8,
    stars: 4.5,
    featured: true,
  },
  {
    id: 96,
    title: "Assistant Photographer",
    description:
      "Work as a part-time assistant photographer and assist in capturing events and portraits. Learn from experienced professionals.Salary will be paid per hour.",
    salary: 300,
    location: "gampaha",
    hours: 7,
    closeDate: "2023-09-30",
    company: "Coastal Moments Photography",
    reviews: 6,
    stars: 4.0,
    featured: false,
  },
  {
    id: 97,
    title: "Assistant Photographer",
    description:
      "Join our photography team as a part-time assistant. Assist in capturing wildlife and natural beauty.Salary will be paid per hour.",
    salary: 450,
    location: "rathnapura",
    hours: 8,
    closeDate: "2023-10-31",
    company: "WildFrames Photography",
    reviews: 5,
    stars: 4.1,
    featured: true,
  },
  {
    id: 98,
    title: "Assistant Photographer",
    description:
      "Work as a part-time assistant photographer and assist in capturing weddings and events. Enhance your photography skills.Salary will be paid per hour.",
    salary: 300,
    location: "kurunagala",
    hours: 9,
    closeDate: "2023-11-30",
    company: "Mirissa Moments Photography",
    reviews: 7,
    stars: 4.2,
    featured: false,
  },
  {
    id: 99,
    title: "Assistant Photographer",
    description:
      "Join our photography team as a part-time assistant. Assist in capturing historical sites and architectural wonders.Salary will be paid per hour.",
    salary: 350,
    location: "colombo",
    hours: 5,
    closeDate: "2024-01-31",
    company: "Heritage Clicks Photography",
    reviews: 6,
    stars: 4.0,
    featured: false,
  },
  {
    id: 100,
    title: "Assistant Photographer",
    description:
      "Be part of our photography team as a part-time assistant. Assist in architectural and real estate photography.Salary will be paid per hour.",
    salary: 400,
    location: "galle",
    hours: 6,
    closeDate: "2023-09-15",
    company: "UrbanScape Photography",
    reviews: 10,
    stars: 4.3,
    featured: true,
  },
];
